sixty-north/cosmic-ray

README.md
cosmic_ray/cli.py
cosmic_ray/commands/execute.py
cosmic_ray/commands/init.py
cosmic_ray/plugins.py
cosmic_ray/tasks/worker.py
cosmic_ray/testing/pytest_runner.py
cosmic_ray/testing/test_runner.py
cosmic_ray/testing/unittest_runner.py
cosmic_ray/timing.py
cosmic_ray/work_db.py
docs/index.md
test_project/cosmic-ray.pytest.conf
test_project/cosmic-ray.unittest.conf

You can now pass a list of arguments to `init` which get passed to the test runner. The test runner can do whatever it liked with the list.

Test plugin args

---

docs/index.md

Currently, on the [docs landing page](http://cosmic-ray.readthedocs.io/en/latest/) the enumerative list resets to `1` at each point. This is because the indentation isn't quite right in the markdown files.
Here is what this PR looks like locally:

Correcting indentation for docs landing page.

---

README.md
docs/index.md
docs/operators.md

Also convert some tabs to spaces, and wrap a paragraph.

Fix a bunch of typos and grammar problems in the documentation.

---

cosmic_ray/cli.py

This makes it easier to use bash tab completion

Allow session-name.json to be passed on the command line

---

cosmic_ray/tasks/worker.py

This has the nice effect of logging stuff into my celery worker's log so I can monitor progress. On my system I get the following output after `celery -A cosmic_ray.tasks.worker worker` has been started and I run `cosmic-ray execute`
```
[2016-07-07 12:25:13,115: WARNING/Worker-2] executing:
[2016-07-07 12:25:13,115: WARNING/Worker-2] ['cosmic-ray', 'worker', 'pykickstart.commands.autopart', 'replace_Eq_with_NotIn', '0', 'unittest', '--', 'tests/']
[2016-07-07 12:25:13,116: WARNING/Worker-1] executing:
[2016-07-07 12:25:13,117: WARNING/Worker-1] ['cosmic-ray', 'worker', 'pykickstart.commands.autopart', 'replace_Eq_with_NotIn', '1', 'unittest', '--', 'tests/']
[2016-07-07 12:25:13,123: WARNING/Worker-3] executing:
[2016-07-07 12:25:13,123: WARNING/Worker-3] ['cosmic-ray', 'worker', …
```

Use Celery's logger for celery tasks

---

cosmic_ray/cli.py
cosmic_ray/modules.py
cosmic_ray/test/test_find_modules.py

This is another minor improvement patch which lets you do things like:
cosmic-ray init --baseline=10 authconfig pykickstart/commands/authconfig.py -- tests/
I find it very handy b/c I'm using tab-completion all the time.

Accept directories and .py files as module names

---

cosmic_ray/cli.py
cosmic_ray/commands/report.py
cosmic_ray/testing/test_runner.py
cosmic_ray/worker.py
setup.py

The idea comes from https://github.com/mbj/mutant - the Ruby mutation testing tool. I've tried to emulate their format as much as possible. I've also added the diff output in case there is an exception so it is easier to debug.  NOTE: The ast parser is stripping out comments, newlines and converting double to single quotes and because of this I'm diff'ing the unparsed value of the original and modifies AST trees. This also leads to difference in line numbers, but still should be easier to navigate than the N-th occurrence of operator X.
An example from one of my test executions:
```
job ID 81:Outcome.SURVIVED:pykickstart.commands.autopart
command: cosmic-ray worker pykickstart.commands.autopart replace_Eq_with_IsNot 3 unittest -- tests/
--- mutation diff ---
--- …
```

Report the mutation results using unified diff format

---

cosmic_ray/commands/report.py

B/c we modify the result_type without this patch the diff output isn't shown.

Properly check for result type when reporting

---

cosmic_ray/testing/unittest_runner.py

This is needed so the reporter can print a nicely formatted traceback when the job is killed.
You can use the Python examples at https://github.com/atodorov/mutation-testing-example to see how results are reported with and w/o this patch. 
Also I'm not sure how the pytest runner will report the failed results and if that wouldn't clash with this existing patch. I don't have a pytest suite ATM but I'll try to make one a give it a try.

Return a list of strings for unittest results, not list of tuples

---

cosmic_ray/cli.py
cosmic_ray/commands/report.py

this makes it possible to keep cleaner output and only reports
diffs for mutations which survived or were incompetent. Use the
--full-report option to show everything if you want.
We can probably extend this to other types of results as well. For now I only want to see the diff for mutants that survived so I can easily spot where I'm missing test cases.
Another possibility is to report only the survived mutants and nothing else. What do you think ?

Don't show test output and mutation diff if result is KILLED

---

cosmic_ray/operators/boolean_replacer.py
cosmic_ray/test/test_operators.py
setup.py
test_project/adam.py
test_project/tests/test_adam.py

@abingham I've fixed a minor issue with the `--full-report` option which you probably want to cherry-pick.
Next I've enabled reports in CI to see what's going on wrong and added a Boolean replacement operator which simply flips `True` and `False` values.
ATM I'm missing tests in `cosmic_ray/test/test_operators.py` b/c I'm not quite sure what is the format.
Also the adam tests are failing b/c there is a `while True:` loop which becomes `while False`. I can modify the loop somehow so we always trigger an infinite loop and not conflict with the BooleanReplacer operator or maybe you can tell me what other tests to add.

Add Boolean replacer

---

cosmic_ray/parsing.py
test_project/cosmic-ray.empty.conf
test_project/run_tests.sh

Running against one of my production SUT I was seeing an error similar to this:
https://travis-ci.org/MrSenko/cosmic-ray/jobs/146085309
With the workaround everything seems to work fine:
https://travis-ci.org/MrSenko/cosmic-ray/jobs/146087865
Note the upstream Python bug http://bugs.python.org/issue27578. I doubt it will get fixed or at least not soon enough, hence the need to workaround.

Workaround for empty __init__.py files

---

cosmic_ray/importing.py
test_project/cosmic-ray.import.conf
test_project/eve/eve.py
test_project/run_tests.sh
test_project/tests/test_eve.py

I believe this fixes my comment at
https://github.com/sixty-north/cosmic-ray/issues/157#issuecomment-233741363
Here is the test log w/o the fix and then with the fix:
https://travis-ci.org/MrSenko/cosmic-ray/jobs/146035928
https://travis-ci.org/MrSenko/cosmic-ray/jobs/146038003

Delete parent modules from sys.modules

---

cosmic_ray/operators/relational_operator_replacement.py

In my experience these two appear to be equivalent and it makes sense to skip this replacement in the same fashion we do for their Not counterparts.
@abingham what do you think ?

Skip  Eq and Is  replacement

---

.travis.yml
setup.py

Python 3.5, 3.5-dev, and nightly build were added, and the tests pass.
Python 3.3 required a change of version for celery, and is still failing.  But could be salvageable.
Python 3.2 does not support `yield from`, so it is unlikely that it is worth the effort to make this work.

Added additional python versions.

---

.travis.yml
cosmic_ray/cli.py
cosmic_ray/operators/boolean_replacer.py
cosmic_ray/test/test_operators.py
cosmic_ray/testing/nose_runner.py
cosmic_ray/testing/pytest_runner.py
cosmic_ray/util.py
setup.py
test_project/adam.py
test_project/run_tests.sh
test_project/tests/test_adam.py

I am submitting these as one PR because I've set out to make the BoolConstReplacer operator 3.3 compatible and then run into some issues.
From #163 
> Python 3.3 required a change of version for celery, and is still failing. But could be salvageable.
@abingham, @degustaf - in `cosmic_ray/importing.py` we make use of `importlib.machinery.ModuleSpec` which was introduced in 3.4. I don't think we can/want to backport this to 3.3 so maybe drop the entire 3.3 compatibility mode ? What do you say ?
@abingham - do you have any preference if I should drop my 3.3 related commits since they will be kind of pointless if we drop this version entirely ?

Python 3.3 fixes and AND/OR mutation operator

---

test_project/cosmic-ray.nosetest.conf

See https://travis-ci.org/sixty-north/cosmic-ray/jobs/159425168 for the actual traceback. I will open an issue report for the fact that we're not returning a non 0 exit code in this case. As a side note almost none of the command handlers appear to be returning error codes which is expected by main(). 
The fix isn't ideal. Because we're running the test suite in verbose mode logs from the baseline execution and all mutations are logged in Travis. With Python 3.5 this is different and I don't see that much logs in verbose mode.

Fix a traceback with Python 3.4 and nose

---

setup.py

this is fixed by requiring TinyDB >= 3.2.1. The particular commit
appears to be https://github.com/msiemens/tinydb/commit/331bb0.
@msiemens would know for sure b/c this is not mentioned in their changelog and the changelog got a bit messed up in the last version.

Prevent modifying session.json when doing cosmic-ray report

---

cosmic_ray/commands/report.py

otherwise we get a long list of the form
job ID XX:Outcome.KILLED:module
command: cosmic-ray worker module ......
which doesn't give much meaningful information but clutters the screen.

Report only SURVIVED mutants if --full-report is not specified

---

cosmic_ray/operators/binary_operator_replacement.py
cosmic_ray/operators/unary_operator_replacement.py
cosmic_ray/test/test_operators.py
setup.py
test_project/adam.py
test_project/tests/test_adam.py

@abingham my previous PR removed all binary operator mutations and this one adds them again. This time we make use of the refactored core and add a lot more possible mutations. Also notice the quick fix of the test suite. The xor in `equals` produces equivalent mutations when replaced with '+' or '-' in this context.

Update mutations for binary operators

---

cosmic_ray/operators/binary_operator_replacement.py
cosmic_ray/operators/comparison_operator_replacement.py
cosmic_ray/operators/unary_operator_replacement.py
cosmic_ray/util.py

This is now handled in `build_mutations()` because it is a common operation. `_to_ops()` needs to only special case mutations depending on context, e.g. ==/is mutation.
@abingham please review

Refactor skipping mutations to self

---

cosmic_ray/cli.py
cosmic_ray/timing.py
test_project/baseline_fail/test_fail.py
test_project/cosmic-ray.baseline_fail.conf
test_project/run_tests.sh

@abingham this is ready for review.
Please note the first commit in this PR. For some reason I was missing the `run_tests.sh` plumbing from #160 so I did cherry-pick of 2718e81 and adjusted for latest syntax. If you can figure out what went wrong I will be interested to hear, especially if you manage to find steps to reproduce. The only thing that comes to mind is accidentally removing this piece of code while dealing with merge conflicts on Jul 24, 2016.

Fail if baseline execution fails

---

.travis.yml
cosmic_ray/importing.py

When using Python 3.6 with cosmic-ray 1.0.0a1, found
that there is a ImportError cause by Python 3.6.
[class importlib.abc.Loader.create_module](https://docs.python.org/3/library/importlib.html#importlib.abc.Loader.create_module)
is now a must to defined in 3.6.
```python
job ID 22:Outcome.KILLED:hello
command: cosmic-ray worker hello number_replacer 0 nose -- test_hello.py
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
raise self.exc_val.with_traceback(self.tb)
File "/usr/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File …
```

Fixed importing ImportError for Python 3.6 and after

---

cosmic_ray/operators/zero_iteration_loop.py
setup.py
test/test_operators.py
test_project/adam.py
test_project/tests/test_adam.py

I am still struggling with 3 issues here:
1. 2 tests are affected: use continue and use break, since they use for.
2. When I mutate manually I see, the tests fail, when I run it as part of the load, it says the mutant is alive. How should I proceed?
3. I do not know how to handle mutant which rely on the return value of the for loop, for example:
```
for i in range(5):
....
return i  
```
This creates incompetent mutants, since i is now UnreferencedLocalVariable.

add zero iteration operator only for for loop

---

.travis.yml

Whatever issue we were seeing seems to have been resolved.

Remove Python 3.5 from travis's "allowed failures".

---

docs/index.md

This PR updates `docs/index.md` with a section detailing the commands `init`, `exec`, and `report`.
The primary purpose is to inform users that:
1. `--verbose` exists and what it does. Currently, it's a little hard to find that information.
2. `cosmic-ray report` can be run while `cosmic-ray exec` is running and will show the current completion percentage, as mentioned in https://github.com/sixty-north/cosmic-ray/issues/219#issuecomment-310427697.

Update docs with details about the various commands

---

README.md

Prevent issues like #224
I know there's a badge, but I tried to run cosmic-ray on a Python 2 project without realising it's Python 3 only.

Mention Python 3 more explicitly

---

cosmic_ray/execution/execution_engine.py
cosmic_ray/testing/test_runner.py

Instead of uselessly throwing exceptions from them, we're just calling pass now.

Properly using @abstractmethod.

---

cosmic_ray/execution/celery.py

You can now configure celery's queue-purging via a configuration values.

Celery purge queue configuration

---

cosmic_ray/cli.py

Takes advantage of the new dedent support in docopt_subcommand to allow
the subcommand docstrings to be formatted more normally.

Regular indentation of subcommand docstrings.

---

cosmic_ray/cli.py

Remove broken symmetry in naming of command handler arguments.
Remove now unnecessary #pylint directives

Use the ununsed arguments in an assert ;-)  

---

cosmic_ray/cli.py

Also calling sys.exit() with error codes from cli's __main__-block.

Returning error codes from cli.main().

---

cosmic_ray/cli.py

Also the version string follows the recommendation is the GNU style guide
that the given name should be the canonical program name, not the filename.

--version now reports the actual version, not a hard-coded string.

---

cosmic_ray/cli.py
cosmic_ray/commands/execute.py
cosmic_ray/commands/format.py
cosmic_ray/commands/init.py
cosmic_ray/execution/execution_engine.py
cosmic_ray/execution/local.py
cosmic_ray/reporting.py
cosmic_ray/testing/test_runner.py
cosmic_ray/work_db.py
cosmic_ray/work_item.py
cosmic_ray/worker.py
plugins/execution-engines/celery3/cosmic_ray_celery3_engine/engine.py
plugins/execution-engines/celery3/cosmic_ray_celery3_engine/worker.py
test/e2e/test_e2e.py
test/unittests/test_command_line_processing.py
test/unittests/test_record.py
test/unittests/test_worker.py

Previously there was a mix of WorkItem, WorkRecord and just 'work'.
I chose WorkItem primarily because it fits better in contexts such
as "pending work items" which sounds like work awaiting completion
compared to "pending work records" which sounds like records waiting
to be inserted.

Consistent work item naming

---

cosmic_ray/cli.py
cosmic_ray/commands/execute.py
cosmic_ray/commands/format.py
cosmic_ray/commands/init.py
cosmic_ray/execution/execution_engine.py
cosmic_ray/execution/local.py
cosmic_ray/progress.py
cosmic_ray/reporting.py
cosmic_ray/testing/test_runner.py
cosmic_ray/work_db.py
cosmic_ray/work_item.py
cosmic_ray/worker.py
plugins/execution-engines/celery3/cosmic_ray_celery3_engine/engine.py
plugins/execution-engines/celery3/cosmic_ray_celery3_engine/worker.py
test/e2e/test_e2e.py
test/unittests/test_command_line_processing.py
test/unittests/test_record.py
test/unittests/test_worker.py

Dependent on #302 (seems to include the same changes as #302 - I guess GitHub isn't smart enough to deal with dependent PRs)
This change makes cosmic-ray respond to SIGINFO while the exec command is running by printing a short progress report to stderr.
Includes a small progress reporting framework which could also be used for the other long-running commands, such as init.

Progress reporting

---

plugins/test-runners/pytest/cosmic_ray_pytest_runner/runner.py

Via the following config:
test-runner:
name: pytest
args:

pytest: handle args=None

---

cosmic_ray/testing/unittest_runner.py

It was added in 96b20fb apparently in an attempt to please pylint it
seems.

UnittestRunner: remove useless-super-delegation

---

.coveragerc
.travis.yml
tox.ini

Fixes https://github.com/sixty-north/cosmic-ray/issues/317.
Running `tox -e py-coverage` locally gives me:
```
----------- coverage: platform linux, python 3.6.3-final-0 -----------
Name                                                  Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------------------
cosmic_ray/cli.py                                       135      7     34      9    89%   105, 110, 131, 196, 316, 331, 357, 104->105, 109->110, 111->131, 195->196, 274->277, 315->316, 327->exit, 330->331, 356->357
cosmic_ray/commands/execute.py                           28      3      4      0    84%   21-23
cosmic_ray/commands/format.py                            64     64     24      0     0%   3-110 …
```

Add coverage reporting via codecov

---

.travis.yml

tox takes care of installation.
This removes the call to `cosmic-ray test-runners`, which should be
covered by a real integration test instead (if not done already).

Travis: remove install section

---

cosmic_ray/config.py

I've tried to run a command from the report ("cosmic-ray worker
module zero_iteration_loop 9") and it was waiting for input on stdin.
This additional logging should help in this case (when run in verbose
mode).

Add logging to load_config

---

cosmic_ray/operators/comparison_operator_replacement.py
cosmic_ray/util.py
test/unittests/test_operators.py

This change avoids creating a whole class of incompetent mutants by detecting when the right-hand side value of a comparison operator is None, and restricting the set of replacement mutant operators to only those which can operate on None.

Detect ast.Compare nodes where the right-hand-side value is None

---

cosmic_ray/testing/test_runner.py
plugins/test-runners/pytest/cosmic_ray_pytest_runner/runner.py

pytest: handle non-zero exit code

---

cosmic_ray/testing/test_runner.py

This makes TestRunnerFailure behave a little better with respect to producing strings. Now it uses Exception's __str__ and __repr__ to produce more meaningful strings.

Reworked test runner failure

---

cosmic_ray/operators/binary_operator_replacement.py
cosmic_ray/operators/comparison_operator_replacement.py
cosmic_ray/operators/unary_operator_replacement.py
cosmic_ray/util.py
test/unittests/test_build_mutations.py

Soon we'll likely need to generate classes dynamically based on (language) operator pairings. For example, rather than have a single class that handles all binary operator mutation, we'll have one per pairing. I expect to use `build_mutations` as part of this work, so this change is about making `build_mutations` ready for it.
Before, `build_mutations` took a sequence of AST node instances and a sequence of types. This won't be possible when we're generating classes because we won't be doing an AST traversal, i.e. we won't have node instances.

Make `build_mutations` amenable to dynamic class generation

---

cosmic_ray/cli.py
cosmic_ray/exit_codes.py
test/unittests/test_command_line_processing.py

This lets us use named exit codes across platforms.

Added an enum with exit-status codes.

---

cosmic_ray/worker.py

This replaces "Reduce ast / run on windows #358"
The problem i experience is explainable by running the typing.py code twice. 
This is what i think happens.:
typing.py gets executed when the unmodified original test code gets loaded
mutation takes place
the preserve_modules context manager deletes typing from the module list 
the mutated code gets loaded, and runs typing again
From now on, on my system at least isinstance(x, Sequence) will trigger an infinit recursion, if there are not more problems. (Why this is not easily reproducible on mac, i do not know)
The proposed solution is to load typing, so it does not get deleted by preserve_modules.

Prevent typing double import

---

cosmic_ray/operators/binary_operator_replacement.py
cosmic_ray/operators/comparison_operator_replacement.py
cosmic_ray/operators/operator.py
cosmic_ray/operators/unary_operator_replacement.py
test/unittests/test_operators.py

The main change here is that the `operator.ReplacementOperator` base class has been replaced by the `operator.ReplacementOperatorMeta` metaclass. This makes the dynamic creation of the various operator-replacement mutation operators look my more normal, i.e. we don't invoke the `type` initializer directly now.
@rob-smallshire I did this after reviewing your "Python Master" chapter on metaclasses, so you should probably review it ;)

Improved machinery for generating operator-replacement operators.

---

docs/commands.rst
docs/concepts.rst
docs/quickstart.rst

In particular, the quickstart docs were out of date, and this had
led (understandably) to some confusion. Hopefully the docs are new a) correct
and b) complete enough for new users.

Improved the new-config documentation.

---

cosmic_ray/cli.py
cosmic_ray/worker.py

Originally we used a worker's stdout to get results, and that was causing problems with e.g. test's that launched subprocesses which wrote to stdout as well. With this change, we use `multiprocessing` to launch worker processes, and we use a pipe to get the results. As a result, we're independent of what happens on stdout. 
This addresses #391 and, hopefully, #386.

Isolated result passing

---

src/cosmic_ray/cloning.py
src/cosmic_ray/exceptions.py
src/cosmic_ray/operators/exception_replacer.py
src/cosmic_ray/operators/provider.py

This re-enables the replace-exception mutation operator.
We now use `sitecustomize.py` to inject our custom exception into testing subprocesses.

Exception replacement

---

docs/source/commands.rst
src/cosmic_ray/cli.py
src/cosmic_ray/modules.py
tests/test_suite/unittests/test_find_modules.py

Implementation of exclude-module
I don't use here interceptor because I don't want to see skipped module in the list of cosmic-ray -v INFO init

Exclude modules

---

src/cosmic_ray/commands/init.py
src/cosmic_ray/work_db.py

The `cosmic-ray init` command takes a lot of time, but that time is mostly spent on waiting for disk synchronisation, not generation of the actual mutation test cases.
this speeds up init execution from over 5 minutes to around 40s on my SSD (and makes it CPU bound, not disk bound)
the last optimisation is rather extreme ("don't use db synchronisation for initial case creation"), but as I've noted in the commit message, the process is not restartable anyway, so there's little point in strict synchronisation

Speed up the init command

---

docs/source/quickstart.rst
src/cosmic_ray/tools/survival_rate.py
src/cosmic_ray/work_db.py
tests/test_suite/unittests/test_work_db.py

Since a non-trivial application will have thousands of mutants, we can execute only some part of it (either based on time or count) and calculate the confidence interval for the estimated mutation score.
Change the runner to execute mutations in random order, extend `cr-rate` with ability to use the estimated mutation score and make it useful for use in CI systems.
fixes #490

Estimate mutation score by sampling

---

docs/source/quickstart.rst

Simply fixing two minor typos.
BTW very nice tool 👍

Fix minor typos in doc/quickstart

---

src/cosmic_ray/tools/html.py
src/cosmic_ray/tools/report.py
src/cosmic_ray/tools/survival_rate.py

Without this patch, in both CLI and HTML result, we would only have 'Survival rate', while people may be interested to know the count of survived mutants as well.
<hr>

Issue 501 - Show Survived Mutant Counts in Reports

---

src/cosmic_ray/tools/filters/operators_filter.py
tests/test_suite/unittests/test_operators_filter.py

WithOUT this patch, if a user (by accident) provides an empty `exclude-operators` in the configuration then applies command `cr-filter-operators`, it will results in that ALL operators to be skipped, while it should not skip any operators.
It's easy to check & confirm this bug:
```python
import re
exclude_operators = []
re_exclude_operators = re.compile('|'.join('(:?%s)' % e for e in exclude_operators))
assert re_exclude_operators.match("abc")
assert re_exclude_operators.match("xyz")
```
Tests are updated/added.

BugFix: empty 'exclude_operators' results in skipping all operators

---

docs/source/tutorials/intro/index.rst
src/cosmic_ray/cli.py

Updated the cli.py file to have the correct reference to excluded-modules and updated the docs to include a brief example of how to use the excluded-modules.
Solves https://github.com/sixty-north/cosmic-ray/issues/525

Issue #525 - Fixing excluded-modules

---

src/cosmic_ray/cli.py
src/cosmic_ray/commands/init.py
src/cosmic_ray/config.py
src/cosmic_ray/mutating.py
src/cosmic_ray/operators/binary_operator_replacement.py
src/cosmic_ray/operators/boolean_replacer.py
src/cosmic_ray/operators/comparison_operator_replacement.py
src/cosmic_ray/operators/example.py
src/cosmic_ray/operators/exception_replacer.py
src/cosmic_ray/operators/keyword_replacer.py
src/cosmic_ray/operators/no_op.py
src/cosmic_ray/operators/number_replacer.py
src/cosmic_ray/operators/operator.py
src/cosmic_ray/operators/provider.py
src/cosmic_ray/operators/remove_decorator.py
src/cosmic_ray/operators/unary_operator_replacement.py
src/cosmic_ray/operators/variable_inserter.py
src/cosmic_ray/operators/variable_replacer.py
src/cosmic_ray/operators/zero_iteration_for_loop.py
src/cosmic_ray/work_db.py
src/cosmic_ray/work_item.py
tests/unittests/test_operators.py

This PR enables users to define mutation operators with arbitrary key word arguments. As an example, the `VariableReplacer` and `VariableInserter` operators have been added. These take two arguments, a `cause_variable: str` and an `effect_variable: str`, and enable the following three types of mutation:
(1) Replacing *all* usages of a specific variable with a random numerical constant (e.g.  `VariableReplacer('x1')` mutates `y=x1+x2+x3+10` to `y=30+x2+x3+10`).
(2) Replacing usages of a specific variable that appear in the statement of another specific variable (e.g. `VariableReplacer(x1, y)` mutates `y=x1+x2+x3+10` to `y=30+x2+x3+10` but does not mutate `j=x1+x2+x3+10`).
(3) Adding usages of a specific variable in the statement of another specific variable (e.g. `VariableInserter(x, y)` …

Mutation operators with arguments (Issue #528)

---

src/cosmic_ray/operators/exception_replacer.py

Without this patch "except (OSError):" leads to an AttributeError. This patch handles this specific example where test_list is an instance of Name.
The tests that already fail (probably since e02b8ec484f00757271e41ac1112a1a599559cb2) still fail, but the added test succeeds.

Make except statment lists work with just one item

---

docs/source/tutorials/intro/index.rst
src/cosmic_ray/cli.py
src/cosmic_ray/modules.py
tests/unittests/test_find_modules.py

I had to estimate how many mutants survive in a huge project where around 400'000 mutations were found. For this I've randomly selected tests and only wanted to mutate the targets of those tests. With the `excluded-modules` this would have been a lot of work. For that I've adapted the code to allow `module-path` to be a list of paths, which will be used as mutation targets.
Since I've already done the work I thought you might be interested in it. If not feel free to discard this PR :)
Additionally, I would expect the tool to abort if the `module-path` is not found and not just do nothing. For an example see: https://github.com/sixty-north/cosmic-ray/blob/e5e0e3b4626da101975fa9ce2be3ce50966c97d2/tests/unittests/test_find_modules.py#L34-L36
Since this changes the behaviour I didn't want to …

Allow module-path configuration to contain multiple paths

---

src/cosmic_ray/modules.py
tests/e2e/test_e2e.py
tests/resources/example_project/cosmic-ray.inexisting.conf
tests/unittests/test_find_modules.py

As mentioned in #533, I'm providing a patch so that the module paths are verified to exist.
An example output of an init command where the module path (`some_inexisting_file` in this case) does not exist:
```bash
$ cosmic-ray init cosmic-ray.toml cosmic-ray.sqlite                                                        
Could not find module path some_inexisting_file
```

Verify that the module paths exist

---

src/cosmic_ray/work_db.py

for the estimation of the survival rate to be representative, the sample must be random, so execute the tasks in random order
see #490 and #491

process work items in random order

---

src/cosmic_ray/tools/filters/git.py
src/cosmic_ray/work_db.py

Because every skipped transaction is committed individually to the DB, it takes extensive amount of time for a database with few tens of thousands of mutants:
without the patch:
```
18.08user 3.50system 1:12.85elapsed 29%CPU (0avgtext+0avgdata 116220maxresident)k
0inputs+1014816outputs (0major+27993minor)pagefaults 0swaps
```
with this patch:
```
10.33user 0.18system 0:10.55elapsed 99%CPU (0avgtext+0avgdata 116008maxresident)k
0inputs+3176outputs (0major+27989minor)pagefaults 0swaps
```
And this is with a fairly fast NVME SSD, slower disk storage will take extensively more time.

cr-filter-git: mark all as skipped in single transaction

---

src/cosmic_ray/tools/survival_rate.py

When using the `cr-rate` in CI, and running tests only for the changed lines, when a PR changes only documentation, the `cr-rate` tool will crash when it's used with the `--estimate` option.
This fixes the issue.

cr-rate: don't crash with no executed and --estimate specified

---

.github/workflows/python-package.yml
README.rst
pyproject.toml
src/cosmic_ray/commands/init.py
src/cosmic_ray/mutating.py
src/cosmic_ray/operators/operator.py
src/cosmic_ray/work_item.py
uv.lock

Python 3.8 had end of life in 07 Oct 2024.
https://endoflife.date/python

Drops Python 3.8 support
