- setup.py
- test_project/run_tests.sh
Minor improvements after latest updates.
> Better error checking for Travis and add missing requirement

- cosmic_ray/__init__.py
- cosmic_ray/cli.py
- cosmic_ray/commands/__init__.py
- cosmic_ray/commands/report.py
- cosmic_ray/counting.py
- cosmic_ray/importing.py
- cosmic_ray/json_util.py
- cosmic_ray/modules.py
- cosmic_ray/mutating.py
- cosmic_ray/operators/arithmetic_operator_deletion.py
- cosmic_ray/operators/break_continue.py
- cosmic_ray/operators/number_replacer.py
- cosmic_ray/operators/operator.py
- cosmic_ray/operators/relational_operator_replacement.py
- cosmic_ray/parsing.py
- cosmic_ray/plugins.py
- cosmic_ray/print_visitor.py
- cosmic_ray/tasks/celery.py
- cosmic_ray/tasks/worker.py
- cosmic_ray/testing/nose_runner.py
- cosmic_ray/timing.py
- cosmic_ray/version.py
- cosmic_ray/work_db.py
- cosmic_ray/worker.py
- setup.py
Fix some issues identified by Landscape.io, mostly cosmetic.
> Fix some code smells & update style

- cosmic_ray/counting.py
- cosmic_ray/mutating.py
- cosmic_ray/operators/arithmetic_operator_deletion.py
- cosmic_ray/operators/boolean_replacer.py
- cosmic_ray/operators/break_continue.py
- cosmic_ray/operators/number_replacer.py
- cosmic_ray/operators/operator.py
- cosmic_ray/operators/relational_operator_replacement.py
- cosmic_ray/test/test_operators.py
These are the updates for #170.
> MutationCore and mutate() updates

- cosmic_ray/operators/exception_replacer.py
- setup.py
- test/test_operators.py
- test_project/adam.py
- test_project/tests/test_adam.py
As discussed in #206  and in the incomplete pull request.
Created a mutator that takes one exception handler and replace it with another.
Current issue:
report phase crashes since diff in the output is null - created another issue to address this
> Exception changer

- cosmic_ray/operators/remove_decorator.py
- setup.py
- test/test_operators.py
- test_project/adam.py
- test_project/tests/test_adam.py
with the exception of class,static and abstract methods
> add decorator remover 

- MANIFEST.in
Fixes https://github.com/sixty-north/cosmic-ray/issues/217
> PR: Add license to manifest

- test_project/run_tests.sh
- set -e
- fix issues reported by shellcheck
> Revisit test_project/run_tests.sh

- .travis.yml
- cosmic_ray/testing/pytest_runner.py
- docs/index.md
"pytest" is the preferred method to run pytest.
> doc: s/py.test/pytest

- pytest.ini
- setup.cfg
This allows for configuring tools in a single file, e.g. flake8 etc
later.
> Move pytest.ini to setup.cfg

- cosmic_ray/commands/execute.py
- cosmic_ray/execution/__init__.py
- cosmic_ray/execution/celery.py
- cosmic_ray/execution/execution_engine.py
- cosmic_ray/execution/local.py
- cosmic_ray/plugins.py
- setup.py
We now expose the local and celery execution engines via plugins.
> Plugins for execution engines

- cosmic_ray/cli.py
- test/test_command_line_processing.py
> Proper usage exit code

- cosmic_ray/cli.py
> Added SIGINT handler that exits with code 0.

- cosmic_ray/cli.py
- cosmic_ray/commands/execute.py
- plugins/execution-engines/celery3/setup.py
- test/unittests/test_command_line_processing.py
Terse error messages instead of stack traces. More useful exit codes.
> Improved robustness of command line handling.

- README.rst
> README: add codecov badge

- cosmic_ray/operators/number_replacer.py
> NumberReplacer now increments and decrements.

- .travis.yml
> Travis: keep running lint,style

- cosmic_ray/operators/binary_operator_replacement.py
- cosmic_ray/operators/comparison_operator_replacement.py
- cosmic_ray/operators/operator.py
- cosmic_ray/operators/provider.py
- cosmic_ray/operators/unary_operator_replacement.py
- cosmic_ray/plugins.py
- docs/operators.rst
- setup.py
- test/test_project/.spor/6d88ea056a814e6ba547a793da7af631.yml
- test/test_project/.spor/c28371c1a85142e1ad34124d39d70f85.yml
- test/test_project/adam.py
- test/unittests/test_command_line_processing.py
- test/unittests/test_operators.py
> Replaced operator plugins with operator provider plugins.

- cosmic_ray/cli.py
- cosmic_ray/plugins.py
> Issue 347 broken logging during plugin loading

- cosmic_ray/cli.py
- test/unittests/test_command_line_processing.py
I isolated the first half of the previous pull request to get it seperated from the removal of the ast reduction
> - replaced constants

- src/cosmic_ray/tools/html.py
> Added timestamp to cr-html output.

- src/cosmic_ray/tools/html.py
Added Summary info in HTML report.
Moved date time to Summary info in HTML report.
Fixed long link to PyCharm in HTML report.
> HTML report

- setup.py
> Set Docopt to 3.0.0 to fix current start issue

- src/cosmic_ray/tools/xml.py
> Issue 451: cr-xml / AttributeError "line_number"

- docs/source/badge.rst
- docs/source/index.rst
- setup.py
- src/cosmic_ray/config.py
- src/cosmic_ray/tools/badge.py
Cosmetic: Creating badge (svg picture useful for CI platforms)
> Add cr-badge to create badge file

- setup.py
- src/cosmic_ray/commands/new_config.py
- src/cosmic_ray/interceptors/pragma_no_mutate.py
According to developers point of views, we can choose spor and/or pragma_no_mutate
> Adding interceptor to disable mutation on line with # pragma: no mutate

- src/cosmic_ray/operators/util.py
- tests/test_suite/unittests/test_util.py
> Adding ASTQuery

- src/cosmic_ray/cli.py
- src/cosmic_ray/commands/execute.py
- src/cosmic_ray/operators/provider.py
- src/cosmic_ray/work_db.py
**Correcting no_op name: NoOp**
Create baseline db with tempfile.mkstemp
cosmic_ray.commands.execute now needs user open db instead of filenaùe
On errors, Write errors in stdout and exit with exit code 1
> NoOp : Add outputs

- docs/source/commands.rst
- docs/source/concepts.rst
- docs/source/distributed.rst
- docs/source/quickstart.rst
- tox.ini
primarily: add documentation about `baseline` command
additionally: general minor fixes to documentation
fixes  #485
> Documentation updates

- docs/source/filters.rst
- setup.py
- src/cosmic_ray/tools/filters/git.py
Add a new 'git-branch' config.
If a branch is given, new code in modules will be mutated
> Add git-branch config

- docs/source/index.rst
This is just a small thing I noticed while reading the documentation.
> Change "actual" to "actually" in `docs/source/index.rst`
